#!/usr/bin/env bash

set -euo pipefail

base=cockroach-$(<VERSION).windows-6.2-amd64

curl -sSfL "https://binaries.cockroachdb.com/$base.zip" > cockroach.zip
7z e cockroach.zip


./bincheck ./cockroach.exe $(<VERSION)
